# Site settings
name: Hao Tian
company: East China Normal Unversity
company2: Department of Computer Science and Software Engineering
location_Eng: Shanghai, China
position: Ph.D. student
github: https://github.com/
facebook: https://www.facebook.com/
email: nicktian.ecnu@gmail.com

baseurl: "/hao-tian-ecnu.github.io/Eng/"

permalink: /:year/:month/:day/:title/

exclude: ['README.md']

# Build settings
markdown: kramdown

